### ISSUE TITLE
Crash not showing and FabricAppUpload

### ISSUE THREAD

**Issue by elibroide** [airext/fabric#1]
Hello,
Thank you for building and publishing that ANE,
It appears that it will save us quite some time connecting our game with Crashlytics.

It appears that the Crashlytics initiates (it sends the current app's version and image) 
but it does not report crashes (upon Crashlytics.getSharedInstance().crash())

Also, I seem to not understand something about the FabricAppUpload.app,
A) What is it for? 
B) How do I know that it had done what it suppose to do (there is no feedback after I finished the guide you left in GitHub)

Thank you very much,
Eli Broide

**Comment by rozd** [comment]
Hello,

Thank you for interest with this project.

The FabricAppUpload.app is the OS X application that uploads your .IPA and .dSYM files to Crashlytics servers to make it available for crash reporting. The reason why we can not tell that everything is okay is that Fabric doesn't provide a script to other special tools to do this, so we need to simulate workflow for Fabric iOS applications.

The problem that you describe with not showing crash report is common due to explanation before. To increase a chance to see crash reports try to:
- upload application through FabricAppUpload.app immediately after .IPA file is built and before it launches;
- try to increase an application version if the first didn't help.

Thanks

**Comment by elibroide** [comment]
Thank you for the quick reply.

I did tested it by changing the app version:
The Fabric dashboard did show the version change, but I still couldn't see a crash after calling crash().

So I deleted my apps from Fabric and now started again:
A new app is not added when I do the following - 
1) Build my app (make an IPA)
2) Run FabricAppUpload.app
3) Upload the app to my phone and start it

It seems that I don't understand the workflow with Crashlytics ANE.
1) Do I do the normal workflow for iOS to add an app? (start a project with xcode and run crashlytics)
2) After building the IPA, do I just run FabricAppUpload.app and then upload the same IPA to my phone to test it?

**Comment by rozd** [comment]
Hi,

Do you have Fabric.app installed on your OS X?

Crash reporting for Crashlytics is a really unclear process, you may find a lot questions about why crash reports aren't in dashboard.

Nevertheless, I'm planning to add support for Android and investigate more elegant solution for upload app files, but I can't promise that this will be soon. Stay tuned.

**Comment by elibroide** [comment]
Their process is a bit troublesome :)

We've currently decided to postpone adding Crashlytics to our game.

But thank you very much, and I'll be checking your repository if we would decide to try again.
